name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: List files
        run: dir
        
      - name: Build
        run: g++ RedSun.cpp -o redsun.exe -v
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: redsun
          path: redsun.exe
